FROM tomcat:9-jre8-alpine
USER root
RUN rm -rf /usr/local/tomcat/webapps/*
ADD config/tomcat-users.xml  /usr/local/tomcat/conf/tomcat-users.xml
ADD config/settings.xml /usr/local/tomcat/conf/settings.xml
ADD config/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
ADD target/author.war /usr/local/tomcat/webapps/ROOT.war
ADD config/server.xml /usr/local/tomcat/conf/server.xml
EXPOSE 8080
CMD ["catalina.sh","run"]


 

